"use Client";

import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
  variable: '--font-roboto'
});

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ `${roboto.className}  font-roboto` }>{children}</body>
    </html>
  );
}
